config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "bills#index"
  resources :users, only: :create
  resources :companies
  resources :bills, only: [:index, :new, :create, :edit, :destroy, :show] do
    resources :invoices, only: [:new, :create, :edit, :destroy]
  end
  get "bills/search"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  #def initialize(user)
  #  can :read, Post, public: true

  #  if user.present?
  #    can :read, Post, user_id: user.index

  #    if user.admin?
  #      can :read, Post
  #    end
  #  end
  #end


  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
         can :access, :rails_admin
       else
         can :manage, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :invoices, dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :bill
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  def index
    @bills = Bill.all
  end

  def show
    @bill = Bill.find(params[:id])
    @invoice = Invoice.new
    @invoices = @bill.invoices
  end

  def new
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      redirect_to root_path
    else
      render :index
    end
  end

  def set_search
    @p = Bill.ransack(params[:q])
    @results =@p.result
  end

  def self.search
    Company.where("company_name LIKE(?)", "%#{search}%") if self !=""
  end

  private

  def bill_params
    params.require(:bill).permit(:bill_item,:bill_price,:bill_unit,:company_name)
  end

  def invoice_params
    params.permit(:invoice_item, :invoice_price, :invoice_unit, :invoice_date,:invoice_count,:company_id, :bill_id)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :user_signed_in?

  def index
  end

  def show
  end

  def new
    @company = Company.new
    @companies = Company.all
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to new_company_path
    else
      render :new
    end
  end

  private

  def company_params
    params.require(:company).permit(:company_name)
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  
  def index
    @form = Invoice.new
  end

  def new
    @form = Invoice.new #Form::InvoiceCollection.new
    #@bill = Bill.find(params[:bill_id])
  end

  def create
    @invoice = Invoice.create(invoice_params) #Form::InvoiceCollection.new(invoice_params)
    if @invoice.save
      redirect_to bills_path
    else
      redirect_to new_invoice_path
    end

  end


    private

    def invoice_params
      params.require(:invoice).permit(:invoice_item, :invoice_price, :invoice_unit, :invoice_date,:invoice_count).merge(bill_id: params[:bill_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/bills/index.html.erb
 <div>
    <h1>SEIKYU!</h1>
    <div>
      <ul>
        <% unless user_signed_in?%>
          <li><%=link_to "Sign in", new_user_session_path %></li>
          <li><%=link_to "Sign up", new_user_registration_path %></li>
        <% else %>
          <li><%=current_user.user_name %>さん</li>
          <li><%=link_to "Sign out", destroy_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>
<body>
  <% if user_signed_in?%>
    <div>
      <%= link_to "顧客追加", new_company_path %>
      <%= link_to "請求書", new_bill_path %>
      <%= link_to "予算", "#"%>
      <%= link_to "詳細", company_path(current_user.id) %>
    </div>
    <div>
      <h1>全体の売上グラフ</h1>
    </div>
    <div>
      <h1>販管費</h1>
    </div>
    <div>
      <h1>利益額</h1>
    </div>
  <% else %>
    <div>
      ログインしたら見れますよー
    </div>
  <% end %>

<h1>請求書</h1>
<%= link_to "テンプレート作成", new_bill_path %>
<%#= link_to "請求書作成", bills_search_path %>
<%= link_to "戻る", root_path %>

<h2>請求書作成</h2>
<%#   <% @bills.each do |bill|%>
    <%#= link_to bill_path(bill.id) do %><br>
      <%# if @bills.present?%>
        <%#= bill.company_name %>
      <%# end %>
    <%# end %>
  <%# end %>

      <%= notice %>
      <%#= column_chart Invoice.group(:invoice_date).sum(result.bill_price) %>

app/views/bills/new.html.erb
<p>テンプレート作成</p>
<%= link_to "戻る", bills_path %>

<%= form_with model:@bill, url:bills_path, local: true do |f|%>
  <%= f.collection_select :company_id, Company.all, :id, :company_name, include_blank:"企業名" %>
  <%= f.text_field :bill_item, placeholder:"請求項目" %>
  <%= f.text_field :bill_price, placeholder:"単価" %>
  <%= f.text_field :bill_unit, placeholder:"単位" %>
  <%= f.submit "更新" %>
<% end %>

<%%>

app/views/bills/search.html.erb
<h1>請求書</h1>

<%= link_to "戻る", bills_path %>

<%= search_form_for @p, url:bills_search_path do |f| %>
  <%= f.collection_select :company_id_eq, Company.all, :id, :company_name, include_blank: "企業選択"%>
  <%= f.submit "作成"%>
<% end %>

  <% if @results.length !=0 %>
    <% @results.each do |result|%>
      <%= f.fields_for :invoices do |i| %>
      
  <%end%>
  <%#= f.text_field :invoice_total, placeholder: "合計"%>
  <%#= f.text_field :invoice_tax, placeholder: "税"%>
  <%#= f.text_area :invoice_comment, placeholder: "備考"%>
<% end %>

app/views/bills/show.html.erb
<h1>請求書</h1>
<%= link_to "戻る", bills_path %>


<%= form_with model:[@bill,@invoice], local: true do |f| %>

  <table>
  <th>
    <td>
      <%= f.text_field :invoice_item,value: @bill.bill_item, placeholder: "請求項目"%>
    </td>
    <td>
      <%= f.text_field :invoice_price,value: @bill.bill_price, placeholder: "単価"%>
    </td>
    <td>
      <%= f.text_field :invoice_count, placeholder: "数量"%>
    </td>
    <td>
      <%= f.text_field :invoice_unit,value: @bill.bill_unit, placeholder: "単位"%>
    </td>
    <td>
      <%= f.date_field :invoice_date, value: Time.now.strftime("%Y-%m-%d") %>
    </td>
    <td>
      <%#= f.text_field :bill_id, value: @bill.id%>
  </th>
  </table>
    <%= f.submit "確定"%>

<%end%>

<% if @invoices.present?%>
<% @invoices.each do |invoice|%>
  <%= invoice.invoice_item%>
  <%= invoice.invoice_price%>
  <span>円</span>
  <%= invoice.invoice_count%>
  <%= invoice.invoice_unit%>
<% end %>
<% end %>

app/views/companies/index.html.erb
<header>
 
  <% end %>
</body>

app/views/companies/new.html.erb
<h1>顧客一覧</h1>
<%= link_to "戻る", root_path %>
<%= form_with model:@company, url:companies_path, local: true do |f|%>
  <%= f.text_field :company_name %>
  <%= f.submit "追加" %>
<% end %>

app/views/companies/show.html.erb
<div>
  <h1>顧客詳細</h1>
</div>
<%= link_to "戻る", root_path %>
<div>
  <ul>
    <li>顧客名</li>
    <li>顧客選択</li>
</div>
<div>
  売上表
</div>
<div>
  販管費
</div>
<div>
  利益額
</div>

app/views/invoices/new.html.erb
<h1>請求書</h1>

<%= link_to "戻る", bills_path %>

<%#= search_form_for @p, url:bills_search_path do |f| %>
  <%#= f.collection_select :company_id_eq, Company.all, :id, :company_name, include_blank: "企業選択"%>
  <%#= f.submit "作成"%>
<%# end %>

<%= form_with model:@invoice, url: invoices_path,method: :post, local: true do |f| %>

      <%#= f.fields_for :invoices do |i| %>
      <table>
      <th>
        <td>
          <%= f.text_field :invoice_item,value: "result.bill_item", placeholder: "請求項目"%>
        </td>
        <td>
          <%= f.text_field :invoice_price,value: "result.bill_price", placeholder: "単価"%>
        </td>
        <td>
          <%= f.text_field :invoice_count, placeholder: "数量"%>
        </td>
        <td>
          <%= f.text_field :invoice_unit,value: "result.bill_unit", placeholder: "単位"%>
        </td>
        <td>
          <%= f.text_field :company_id,value: "result.company_id" %>
        </td>
        <td>
          <%= f.date_field :invoice_date, value: Time.now.strftime("%Y-%m-%d") %>
        </td>
      </th>
      </table>
      <%#end%>
    <%#end%>
  <%#end%>
  <%#= f.text_field :invoice_total, placeholder: "合計"%>
  <%#= f.text_field :invoice_tax, placeholder: "税"%>
  <%#= f.text_area :invoice_comment, placeholder: "備考"%>
  <%= f.submit "確定"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>